# Generated by Django 2.0 on 2020-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=1, max_digits=5)),
                ('expenses', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
